### ISSUE TITLE
SLimeTinker Spam cón

### ISSUE THREAD

**Issue by lonng12** [Sefiraat/SlimeTinker#178] opened 2023-07-17 07:31 UTC
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

[14:25:58 ERROR]: Could not pass event EntityDamageByEntityEvent to SlimeTinker vDEV - 82 (git cc248acd)
java.lang.NullPointerException: null
[14:25:58 ERROR]: Could not pass event EntityDamageByEntityEvent to SlimeTinker vDEV - 82 (git cc248acd)
java.lang.NullPointerException: null
[14:25:58 ERROR]: Could not pass event EntityDamageEvent to SlimeTinker vDEV - 82 (git cc248acd)
java.lang.NullPointerException: null
[14:25:59 ERROR]: Could not pass event EntityDamageEvent to SlimeTinker vDEV - 82 (git cc248acd)
![image](https://github.com/Sefiraat/SlimeTinker/assets/74055318/de930faa-5218-4e22-bbc4-30996f642c17)

### Steps to reproduce

![image](https://github.com/Sefiraat/SlimeTinker/assets/74055318/63ee3102-784c-407d-b80a-441ede8a056f)

### Expected behavior

fix bug spam console,
Thank you dev

### Server software

Purpur

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

DEV - 1087

### SlimeTinker version

Dev - 82

### Other plugins

[14:31:30 INFO]: Paper Plugins: (1):
[14:31:30 INFO]:  - RoseStacker
[14:31:30 INFO]: Bukkit Plugins: (135):
[14:31:30 INFO]:  - AdvancedBan, AdvancedEnchantments, *AdvancedReplay, AdvancedTech, AlchimiaVitae, AnimatedScoreboard, AntiCheatReplay, antiRedstoneClock, AuctionHouse, AureliumSkills
[14:31:30 INFO]:  AutoTool, BanAnnouncer, BanItem, BetterReactor, BetterRTP, BetterTeams, bloodmoon-advanced, BossShopPro, Brewery, Bump
[14:31:30 INFO]:  BungeeGuard, *ChatGames, ChatManager, ChestShop, ClearLag, CMILib, ColoredEnderChests, CompressionCraft, ConsoleSpamFix, CoreProtect
[14:31:30 INFO]:  Essentials, EssentialsGeoIP, EssentialsSpawn, ExcellentCrates, ExoticGarden, ExtraGear, ExtraTools, FastChunkPregenerator, floodgate, FlowerPower
[14:31:30 INFO]:  FluffyMachines, FNAmplifications, FoxyMachines, Galactifun, Gastronomicon, GlobalWarming, GriefPrevention, GSit, HotbarPets, Images
[14:31:30 INFO]:  InfinityExpansion, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, ItemsAdder, Jobs, LightAPI, Liquid, LiteXpansion
[14:31:30 INFO]:  LoneLibs, LuckPerms, MechanicsCore, MiniBlocks, MissileWarfare, MobCapturer, Multiverse-Core, NapTheMomo, Netheopoiesis, Networks
[14:31:30 INFO]:  NexEngine, OnePlayerSleep, PlaceholderAPI, PlayerPoints, PlayerStats, PlayerWarps, PluginManager, PotionExpansion, ProtocolLib, RealisticSeasons
[14:31:30 INFO]:  RelicsOfCthonia, RewardsLite, SFAdvancements, SFCalc, SfChunkInfo, Shopkeepers, SilkSpawners_v2, SimpleMaterialGenerators, SimpleStorage, SimpleUtils
[14:31:30 INFO]:  Skript, SlimeCustomizer, Slimefun, SlimefunLuckyBlocks, SlimefunOreChunks, SlimefunWarfare, SlimeHUD, SlimeTinker, SlimyRepair, SlimyTreeTaps
[14:31:30 INFO]:  SmallSpace, SoulJars, SoundMuffler, spark, Spicord, SpiritsUnchained, Supreme, T2C-OPSecurity, T2CodeLib, TAB
[14:31:30 INFO]:  Terra, Thesieutoc, TradeSystem, TranscEndence, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, VillagerTrade, VillagerUtil
[14:31:30 INFO]:  Vulcan, Wildernether, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by ybw0014** [comment] 2023-07-18 23:16
without the full stack trace we cannot identify the cause, sorry

**Comment by lonng12** [comment] 2023-07-25 14:55
what do i need to add

**Comment by ybw0014** [comment] 2023-07-25 15:59
These stack traces cant help us identify the cause, try to find one with full stack trace. Maybe disabling the stack trace remover would help.

**Comment by ybw0014** [comment] 2023-08-01 14:12
No useful information provided, closing

**Closed by ybw0014** 2023-08-01 14:12 UTC
Labels: bug
