### ISSUE TITLE
Duplicate noteblock from custom ore

### ISSUE THREAD

**Issue by DarrienZ** [Sefiraat/SlimeTinker#185] opened 2023-09-02 16:14 UTC
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

They can get the note block by using "Explosive Pickaxe" from SlimeTinker.

Video: https://youtu.be/lVH2mZyXhi8

https://github.com/Slimefun/Slimefun4/issues/3836

Using Pufferfish server jar 1.20.1
Using ItemsAdder to create custom items

### Steps to reproduce

-

### Expected behavior

- 

### Server log

https://pastebin.com/LJdiJiT1

### Error report

No Error

### Server software

Other (please specify in your description)

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

Slimefun DEV - 1097 (git 67af02ce)

### SlimeTinker version

SlimeTinker vDEV - 84 (git 2c9f6155)

### Other plugins

Pufferfish git-Pufferfish-23 (MC: 1.20.1)
Slimefun DEV - 1097 (git 67af02ce)
Metrics-Module #29
Java 18
Installed Addons: (8)
  InfinityExpansion vDEV - 144 (git 9da37202)
  LiteXpansion vDEV - 191 (git 61c517b4)
  FoxyMachines vDEV - 67 (git 0028aa93)
  AdvancedEnchantments v9.3.16
  SlimeTinker vDEV - 84 (git 2c9f6155)
  CMI v9.6.2.6
  ItemsAdder v3.5.0c-r4
  ExoticGarden vDEV - 78 (git 7f9a5f63)

**Comment by DarrienZ** [comment] 2023-09-08 14:42
Hmmm

**Comment by ybw0014** [comment] 2023-09-09 19:21
Duplicate of #150

**Closed** 2023-09-09 19:40 UTC
Labels: bug

**Comment by DarrienZ** [comment] 2023-09-09 21:47
Already using DEV 1100
[21:47:32 INFO]: Slimefun version DEV - 1100 (git d683a633)
[21:47:32 INFO]: Slimefun basically turns your entire Server into a FTB modpack without installing a single mod
[21:47:32 INFO]: Website: https://github.com/Slimefun
[21:47:32 INFO]: Author: The Slimefun 4 Community
