### ISSUE TITLE
Errors on server with PaperSpigot 1.20.2

### ISSUE THREAD

**Issue by wpmidia** [Sefiraat/SlimeTinker#194] opened 2023-12-07 23:26 UTC
### Checklist

- [X] I am using official English version of SlimeTinker and did not modify jar.
- [X] I am using an up to date "DEV" version of SlimeTinker.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### Description

**Server Info: 1.20.2-R0.1-SNAPSHOT/git-Paper-318 (MC: 1.20.2)**

`[20:10:24 INFO]: [SlimeTinker] [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
[20:10:24 INFO]: [SlimeTinker] [ACF] java.lang.NoSuchFieldException: locale
[20:10:24 INFO]: [SlimeTinker] [ACF]    at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at SlimeTinker - DEV 84 (git 2c9f6).jar//io.github.sefiraat.slimetinker.acf.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:317)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at SlimeTinker - DEV 84 (git 2c9f6).jar//io.github.sefiraat.slimetinker.acf.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:57)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.players.PlayerList.a(PlayerList.java:346)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[20:10:24 INFO]: [SlimeTinker] [ACF]    at java.base/java.lang.Thread.run(Thread.java:833)`

### Steps to reproduce

I only started the server after updated the Paper Spigot to 1.20.2

### Expected behavior

No errors!

### Server log

https://paste.helpch.at/baliluyazi.md

### Server software

Spigot

### Minecraft Version

1.19.x

### CS-CoreLib Version

- [X] I don't have CS-CoreLib installed

### Slimefun version

Slimefun4 - DEV 1104 (git c9774)

### SlimeTinker version

SlimeTinker - DEV 84 (git 2c9f6)

### Other plugins

https://paste.helpch.at/zubuqucubi

**Comment by ybw0014** [comment] 2023-12-08 03:43
Duplicate of #190

**Closed by ybw0014** 2023-12-08 03:43 UTC
Labels: bug

**Comment by wpmidia** [comment] 2023-12-10 11:15
Sorry, but I didn't understand anything. Is there a resolution to the problem or not? 

Duplicate of #190 is not clear for me. I'm not a developer! Sorry. :(
